# Generated by Django 4.2 on 2023-04-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0003_alter_seller_options_alter_sellercreditorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=15)),
                ('credit', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Sim Card',
                'verbose_name_plural': 'Sim Cards',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SimCreditOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
                ('sim_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.simcard')),
            ],
            options={
                'verbose_name': 'Sim Card Credit Order',
                'verbose_name_plural': 'Sim Card Credit Orders',
                'ordering': ('-created_at',),
            },
        ),
    ]
