# Generated by Django 4.2 on 2023-04-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellercreditorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('-created_at',), 'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AlterModelOptions(
            name='sellercreditorder',
            options={'ordering': ('-created_at',), 'verbose_name': 'Seller Credit Order', 'verbose_name_plural': 'Seller Credit Orders'},
        ),
    ]
